version: '3.7'

services:
  frontend:
    container_name: frontend-dev
    build:
      context: ./toiletprojectfrontend/toilettapp
      dockerfile: Dockerfile
    volumes:
      - './toiletprojectfrontend/toilettapp/src:/src'
      - './toiletprojectfrontend/toilettapp/public:/public'
 #     - '/node_modules'
    ports:
      - 3001:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
