version: '3.7'

services:
  frontend:
    container_name: frontend-dev
    build:
      context: ./toiletprojectfrontend
      dockerfile: Dockerfile
    volumes:
      - './toiletprojectfrontend/react-form-handling/public:/public'
 #     - '/node_modules'
    ports:
      - 3001:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
