version: '3.7'

services:
  db:
    container_name: db-dev
    hostname: db-dev
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Yrgo2021
    ports:
      - 3306:3306
    volumes:
      - './dbVolume:/var/lib/mysql'
  frontend:
    container_name: frontend-dev
    hostname: frontend-dev
    build:
      context: ./toiletprojectfrontend/toilettapp
      dockerfile: Dockerfile
    volumes:
      - './toiletprojectfrontend/toilettapp/src:/src'
      - './toiletprojectfrontend/toilettapp/public:/public'
 #     - '/node_modules'
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
  backend:
    container_name: backend-dev
    hostname: backend-dev
    depends_on:
      - db
    build:
      context: ./toiletprojectbackend
      dockerfile: Dockerfile
    #volumes:
     #- './toiletprojectbackend/build/libs/toiletproject-0.0.1-SNAPSHOT.war:/usr/local/tomcat/webapps/toiletproject-0.0.1-SNAPSHOT.war'
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db-dev:3306/toiletdb?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Yrgo2021
    ports:
      - 9091:8080
    links:
      - db:db