version: '3.7'

services:
  frontend:
    container_name: frontend-dev
    hostname: frontend-dev
    build:
      context: ./toiletprojectfrontend/toilettapp
      dockerfile: Dockerfile
    volumes:
      - './toiletprojectfrontend/toilettapp/src:/src'
      - './toiletprojectfrontend/toilettapp/public:/public'
 #     - '/node_modules'
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
  backend:
    container_name: backend-dev
    hostname: backend-dev
    build:
      context: ./toiletprojectbackend
      dockerfile: Dockerfile
    volumes:
      - './toiletprojectbackend/build/libs/toiletproject-0.0.1-SNAPSHOT.war:/usr/local/tomcat/webapps/toiletproject-0.0.1-SNAPSHOT.war'
    ports:
      - 8081:8080
      - 5050:5050
      - 9091:9091
  db:
    container_name: db-dev
    hostname: db-dev
    image: mysql
    ports:
      - 3305:3306
    command: --init-file /data/application/init.sql
    volumes:
      - './init.sql:/data/application/init.sql'
      - './dbVolume:/var/lib/mysql'
    restart: always
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: homies
      MYSQL_USER: bajs
      MYSQL_PASSWORD: Yrgo2021
